### ISSUE TITLE
Bulk records

### ISSUE THREAD

**Issue by alejandrocortes3112** [mlockett/ApexLogger#3]
Hi @mlockett, how do you handle the case of a developer calling LogService inside a loop?

Thank you!

**Comment by mlockett** [comment]
Hi, @alejandrocortes3112. I would not use it directly inside a loop unless you know it's a relatively small loop, otherwise, you might hit platform event limits. It might be acceptable if you are only logging the time in the loop when there is a failure.

One option would be to create a string before the loop, then each time through the loop, append your data to the string, and then after the loop, log the message using the string.

Another option would be to create event objects--you don't need to publish the events--simply create them in the loop and add them to a list. At the end of the loop, use the _Logger.insertAppLogs_ method to write all the records in a single step.

I hope that helps.
